name: Build/release

on:
  push:
    tags:
      - 'v*'
  schedule:
    - cron: '0 10 * * *'
  workflow_dispatch:


jobs:
  release:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60

    env:
      is_tag: ${{ startsWith(github.ref, 'refs/tags/v') }}
      SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPCRAFT_TOKEN }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
#        os: [windows-latest]

    steps:
      # Windows fix. See https://github.com/actions/checkout/issues/226
      - run: git config --global core.autocrlf false

      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'yarn'

       # Because of timeout issue https://github.com/yarnpkg/yarn/issues/4890
      - run: yarn install --immutable --network-timeout 1000000

      - name: (Linux) Install and login to Snapcraft
        uses: samuelmeuli/action-snapcraft@v2
        if: startsWith(matrix.os, 'ubuntu')

      - name: Save provisioning profile
        if: startsWith(matrix.os, 'macos')
        env:
          PROVISIONING_PROFILE_BASE64: ${{ secrets.PROVISIONING_PROFILE_BASE64 }}
        run: |
          echo -n "$PROVISIONING_PROFILE_BASE64" | base64 --decode > LosslessCut_Mac_App_Store_provisioning_profile.provisionprofile

      - name: (Windows) Download ffmpeg
        if: startsWith(matrix.os, 'windows')
        run: yarn download-ffmpeg-win32-x64

      - name: (Linux) Download ffmpeg
        if: startsWith(matrix.os, 'ubuntu')
        run: yarn download-ffmpeg-linux-x64

      - name: Build/release Electron app
        uses: samuelmeuli/action-electron-builder@v1
        with:
          # GitHub token, automatically provided to the action
          # (No need to define this secret in the repo settings)
          github_token: ${{ secrets.github_token }}

          # If the commit is tagged with a version (e.g. "v1.0.0"),
          # release the app after building
          release: ${{ env.is_tag == 'true' }}

          max_attempts: 1

          mac_certs: ${{ secrets.mac_certs }}
          mac_certs_password: ${{ secrets.mac_certs_password }}

